mesa: i830: Fix -Wxor-used-as-pow build Werror on AOSP
This one is most likely a false positive because it looks
like "^" operator is indeed used for XOR operation in the
surrounding code context and not as POW operator.

"mode ^= (0x2 ^ 0x3);" worked, but making CULLMODE*
variables a hex constant did not do the trick. Using the
XOR result "1" (CULLMODE_NONE) seem like a reasonable
solution to silence the following build Werror:

"
src/mesa/drivers/dri/i915/i830_state.c:605:31: \
    error: result of 'CULLMODE_CW ^ CULLMODE_CCW' is 1; did you mean '1 << CULLMODE_CCW' (8)? [-Werror,-Wxor-used-as-pow]
         mode ^= (CULLMODE_CW ^ CULLMODE_CCW);
                  ~~~~~~~~~~~~^~~~~~~~~~~~~~
                  1 << CULLMODE_CCW
src/mesa/drivers/dri/i915/i830_state.c:605:31: \
    note: replace expression with '0x2 ^ CULLMODE_CCW' to silence this warning
"

Suggested-by: John Stultz <john.stultz@linaro.org>
Signed-off-by: Amit Pundir <amit.pundir@linaro.org>
Change-Id: I3622162a89196db90aca44e0f417c6b4db97e9a1